language: python
python:
  - "3.7"
install:
  - pip install -r backend/requirements.txt
  - (cd frontend && npm install)
script:
  - (cd frontend && npm test)
  - (cd backend && python manage.py test)
notifications:
  email:
  - wx2227@gmail.com