matrix:
  include:
    - language: python
      python:
        - "3.7"
      install:
        - pip install -r backend/requirements.txt
      script:
        - (cd backend && python manage.py test)
        - (cd backend && coverage run manage.py test)

    - language: node_js
      node_js:
        - "10.15.3"
      install:
        - cd frontend && npm install
      cache:
        directories:
          - frontend/node_modules
      script:
        - npm test
notifications:
  email:
  - wx2227@columbia.edu