# Generated by Django 3.0.8 on 2020-11-13 09:21

from django.db import migrations, models
import django.db.models.deletion
import sharednote.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(default='')),
                ('file_url', models.TextField()),
                ('description', models.TextField(default='')),
                ('course_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sharednote.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('lion_mail', models.EmailField(max_length=254, validators=[sharednote.models.validate_lion_mail])),
                ('avartar', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UpVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ups', to='sharednote.Note')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharednote.User')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sharednote.User'),
        ),
        migrations.CreateModel(
            name='DownVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downs', to='sharednote.Note')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharednote.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sharednote.Note')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharednote.User')),
            ],
        ),
    ]
