# Generated by Django 3.0.8 on 2020-11-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharednote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeuser',
            name='avatar',
            field=models.TextField(default='', max_length=200, null=True),
        ),
    ]
