# Generated by Django 3.1.3 on 2020-11-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharednote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_name',
            field=models.TextField(default=''),
        ),
    ]
