# Generated by Django 3.0.8 on 2020-11-28 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharednote', '0002_auto_20201125_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.IntegerField(choices=[(1, 1), (0, 0)], default=0)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharednote.Note')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'note_id')},
            },
        ),
    ]
