# Generated by Django 3.0.8 on 2020-12-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharednote', '0002_customizeuser_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeuser',
            name='nick_name',
            field=models.TextField(default='Acozekypo', max_length=30),
        ),
    ]
