# Generated by Django 3.0.8 on 2020-11-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharednote', '0003_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user_info',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user_info', 'note_id')},
        ),
    ]
