# Generated by Django 3.0.8 on 2020-12-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharednote', '0003_auto_20201201_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='url',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customizeuser',
            name='nick_name',
            field=models.TextField(default='Ymuputiwa', max_length=30),
        ),
    ]
