# Generated by Django 3.0.8 on 2020-11-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharednote', '0004_auto_20201128_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user_info',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user_id', 'note_id')},
        ),
    ]
