# Generated by Django 3.0.8 on 2020-11-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharednote', '0005_auto_20201128_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizeuser',
            name='nick_name',
            field=models.TextField(default='Itydese', max_length=30),
        ),
    ]
